### PR TITLE
`totalCells` moved to `hits[*].cellSuspensions`

### LINKED ISSUE #252: Incorrect cell count/specimens displayed in staging UI
In the staging Browser, I am viewing the project "Healthy and type II diabetes pancreas" which is a SmartSeq2 experiment that has data from 10 pancreas tissue samples from which 3,514 cells were sequenced. Because this is a SS2 experiment, each cell suspension contains a single cell. In the view of this project (screenshot below), the 10 pancreas tissue samples are displayed, but each tissue is shown to have 1 cell in the Cell Count (Estimated) column. This is incorrect. Each tissue produced many cells, although you'd have to aggregate (sum) the number of cell suspensions linked to each tissue to get the count. They likely are not all the same count.

Not sure if this is a bug or whether this view is an intermediate step towards figuring out how to display SS2 experiments in the Browser. Though I'd make a ticket anyway :grinning:

screen shot 2018-10-04 at 11 52 18

┆Issue Number: HCAB-225

### PR DESCRIPTION
**Pull request by hannes-ucsc**
Don't merge this now or at all. It's meant as a heads-up to what's coming down the pipe as a fix to https://github.com/DataBiosphere/azul/issues/499 which will ultimately fix #252.

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
This change works for the Specimens tab but not for the Files tab even though the service response is of the same shape for bot and has cell suspensions with cell counts populated.

**Comment by hannes-ucsc** [comment]
The Azul changes this PR follows-up on are currently deployed here:

https://service.hannes.dev.explore.data.humancellatlas.org/

**Comment by NoopDog** [comment]
@hannes-ucsc on dev i am now taking the cellSuspensions.totalCellCount as the  Total Cell Count (Estimated) for project, specimen and file. For project this ignores the project summary.

Let me know if this is what  you wanted and if I should promote this change to higher environments. 

Cheers,
D

**Comment by NoopDog** [comment]
closing as this is now redundant to the solution on dev.

**Pull request closed without merging**
