### PR TITLE
feat: using error component #854

### LINKED ISSUE #854: Update ErrorBoundary fallback render to use Error component
Update the `_app.tsx` `ErrorBoundary` `fallbackRender` to use the `Error` component.

### Approach
- Use the `Error` component from `@clevercanary/data-explorer-ui` package.
- Configure props to pass to the component:
  - `errorMessage`,
  - `requestUrlMessage` and
  - `rootPath` (configured `redirectRootToPath` and possibly `NEXT_PUBLIC_BASE_PATH` if required?).
- Map any Axios errors as early as possible to a standard error type; no one outside of the service should need to know about Axios.

### Definition of Done
- Render Error component from `@clevercanary/data-explorer-ui` package when an error is thrown.
- Any Axios related errors are mapped as early as possible to a standard error type.

### PR DESCRIPTION
**Pull request by BruceRodrigues**
### Ticket
Closes https://github.com/clevercanary/data-browser/issues/854

### Reviewers
@.

### Changes
- Removing the use of TempError comonent
- Using new Error component from data-explorer package

### CODE REVIEW

**Comment by BruceRodrigues** [comment]
@frano-m I'm having some problems testing this, I'm getting an error related to the Error component. Do you have any idea what might be causing it?
Screen Shot 2023-05-17 at 21 56 34

**Comment by NoopDog** [comment]
@BruceRodrigues, the Error component is now merged in data-explorer-ui 0.21.0 and is on main. Can you retest and re-submit this for review if it looks ok? Thanks! D

**Comment by BruceRodrigues** [comment]
The branch was updated and tested.

Screenshot 2023-08-21 at 20 34 22

**Comment by NoopDog** [comment]
Sorry @BruceRodrigues can you see if this PR is still required and if so rebase it and test?

**Comment by BruceRodrigues** [comment]
Hey @NoopDog, this is still necessary. Currently, this is the ErrorComponent we're using for data-browser
Screenshot 2023-10-14 at 20 46 30
and this PR will change it to 
Screenshot 2023-10-14 at 20 49 18

However, I have found an issue with this component, if you click to "To Homepage" the error component is still presented. I've investigated a little bit about what causing this and to fix it we would need to change some things on ExploreState, so I would like to check first if this should be done already, and if so, should I do it on this PR?

**Review by frano-m — APPROVED** [review]
LGTM! Thank you @BruceRodrigues

**Comment by MillenniumFalconMechanic** [comment]
Merged manually.

**Pull request closed without merging**
