### PR TITLE
Create FedRAMP 3PAO pen test deployment (Databiospere/azul#6246)

### PR DESCRIPTION
**Pull request by hannes-ucsc**

### CODE REVIEW

**Review by frano-m — APPROVED** [review]
LGTM thanks @hannes-ucsc 🌟.

As a side-note - I wondered whether you intentionally want the `browserUrl` value passed in to `makeConfig` to be different to `NEXT_PUBLIC_SITEMAP_DOMAIN'? I haven't reviewed the gitlab files but the config looks great. Thanks.

**Comment by hannes-ucsc** [comment]
> As a side-note - I wondered whether you intentionally want the browserUrl value passed in to makeConfig to be different to `NEXT_PUBLIC_SITEMAP_DOMAIN'?

Good catch. Fixed.

**Comment by hannes-ucsc** [comment]
Can I merge this?

**Comment by NoopDog** [comment]
Yes, this is approved. Rebase and merge!
Cheers,
D

**Pull request merged**
