### PR TITLE
chore: resolving npm vulnerabilities #444

### LINKED ISSUE #444: 404 Page for Data Browser
Go to a project tab like https://dev.data.humancellatlas.org/explore/projects/f78e4798-2744-4613-9df4-a6866e1da805

Modify the url to garbage like https://dev.data.humancellatlas.org/explore/projects/f78e4798-2744-4613-9df4-JUNK

Then refresh.. we get a blank page instead of a 404 page.

┆Issue Number: HCAB-361

### LINKED ISSUE #444: Resolve NPM package security issues

### PR DESCRIPTION
**Pull request by BruceRodrigues**
### Ticket
Closes [#444](https://github.com/clevercanary/data-explorer/issues/444)
Vulnerabilities reduced to 1 low and 2 moderate

### Reviewers
@.

### Changes
- Added
- Removed
- Modified

### CODE REVIEW

**Comment by NoopDog** [comment]
@jpaten can you run the smoke tests manually on this PR? The smoke tests are not merged yet. I guess that would mean you have to rebase your smoke tests branch on this PR and then run them.  Thanks!

**Comment by NoopDog** [comment]
@frano-m can you test this locally, please? 
Thanks, D

**Comment by NoopDog** [comment]
OK, it looks like we still need this.

**Comment by BruceRodrigues** [comment]
I have opened this new PR https://github.com/DataBiosphere/data-browser/pull/3735 with DataBiosphere repo as origin.

**Pull request closed without merging**
