### PR TITLE
Bruce/910 fixing error component

### LINKED ISSUE #910: local integration test is not local
`local_integration_test` should probably be renamed to something like `azul_integration_test`.

### LINKED ISSUE #910: Update ErrorBoundary component to allow the error to be cleared
- Update key to prevent component re-render.
- Sometimes the URL (generated for example, from filtering) causes an error, and in this instance, we will need to clear the filter.

### PR DESCRIPTION
**Pull request by BruceRodrigues**
### Ticket
Closes [#910](https://github.com/clevercanary/data-browser/issues/910)

### Reviewers
@.

### Changes
- Modified `ErrorBoundary` to force rerender when path changes

### CODE REVIEW

**Comment by BruceRodrigues** [comment]
@frano-m @NoopDog to complete this, we need to merge [this PR](https://github.com/clevercanary/data-explorer/pull/446) on `data-explorer` and update the package version here.

**Review by frano-m — APPROVED** [review]
LGTM! @BruceRodrigues thank you!

**Comment by NoopDog** [comment]
Sorry @BruceRodrigues can you redo this from DataBiosphere ?

**Comment by BruceRodrigues** [comment]
This PR was moved to this one https://github.com/DataBiosphere/data-browser/pull/3754 created from DataBiosphere

**Pull request closed without merging**
